jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn test
    strategy:
      matrix:
        java-version:
        - 8
        - 9
        - 11
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
